name: Check Templates and Publish

on:
  push:
    branches: [master, dev, test-me-*]
    tags: [v*]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run Scripts
      run: |
        poetry run tox

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build and Publish distribution 📦to PyPI
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_PASSWORD }}
        poetry publish --build